[theme]
base = "light"
primaryColor = "#ff4b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[ui]
hideTopBar = false
hideSidebarNav = false

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
