name: Deployment Test
on: workflow_dispatch
jobs:
    main:
        name: Build package with Poetry and run example Constrain script
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install poetry
              uses: abatilo/actions-poetry@v2
            - name: Setup a local virtual environment (if no poetry.toml file)
              run: |
                poetry config virtualenvs.create true --local
                poetry config virtualenvs.in-project true --local
            - uses: actions/cache@v3
              name: Define a cache for the virtual environment based on the dependencies lock file
              with:
                path: ./.venv
                key: venv-${{ hashFiles('poetry.lock') }}
            - name: Install the project dependencies
              run: poetry install
            - name: Build package
              run: poetry build
            - name: Install package
              run: python -c "import glob, subprocess; [subprocess.call(['pip', 'install', f]) for f in glob.glob('./dist/*.whl')]"
            - name: Run sample ConStrain script
              run: cd ..; python ./ConStrain/.github/workflows/sample_constrain_run.py
            
